draw_sprite_ext(sprite_index,0,x,y,1,1,0,color,1);
draw_set_color(color);
draw_circle(x,y,radius,true);
draw_line(x-radius,y,x+radius,y);
draw_set_color(c_red);
draw_circle(x,y,col_radius,true);
draw_line(x-col_radius,y,x+col_radius,y);
draw_set_color(c_black);
draw_rectangle(x-col_radius,y-1,x+col_radius,y-col_radius,false);